apiVersion: v1
kind: Pod
metadata:
  name: requests-limits-demo-too-much-memory
spec:
  containers:
  - name: requests-limits-demo-too-much-memory
    image: polinux/stress
    resources:
      requests:
        memory: "150Mi"
        cpu: "200m"
      limits:
        memory: "200Mi"
        cpu: "400m"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
